train:
  _target_: src.datasets.DatasetCombine
  datasets:
    - _target_: src.datasets.BarkopediaDataset
      part: train
      train_split: 0.9
      instance_transforms: ${transforms.instance_transforms.train}

    - _target_: src.datasets.Dog2VecDataset
      part: train
      train_split: 0.8
  dataset_names:
    - barkopedia
    - dog2vec


backend_test_dataset:
  _target_: src.datasets.DatasetCombine
  datasets:
    - _target_: src.datasets.BarkopediaDataset
      part: "test"
      instance_transforms: ${transforms.instance_transforms.inference}
    # - fit_split: 0.15

fit_backend:
  _target_: src.datasets.TestBackend
  dataset: ${datasets.backend_test_dataset}
  part: "fit"
  fit_split: 0.15
  seed: ${trainer.seed}

test_backend:
  _target_: src.datasets.TestBackend
  dataset: ${datasets.backend_test_dataset}
  part: "test"
  fit_split: 0.15
  seed: ${trainer.seed}
#TODO