train:
  _target_: src.datasets.DatasetCombine
  datasets:
    - _target_: src.datasets.Dog2VecDataset
      part: "train"
      train_split: 0.7
      data_dir: null
      max_videos_per_breed_context: 10
      random_seed: ${trainer.seed}
      instance_transforms: ${transforms.instance_transforms.train}


val:
  _target_: src.datasets.DatasetCombine
  datasets:
    - _target_: src.datasets.Dog2VecDataset
      part: "val"
      train_split: 0.7
      data_dir: null
      max_videos_per_breed_context: 10
      random_seed: ${trainer.seed}
      instance_transforms: ${transforms.instance_transforms.inference}
    - _target_: src.datasets.BarkopediaDataset
      part: "val"
      train_split: 0.0
      hub_workers: 1
      data_dir: null
      random_seed: ${trainer.seed}              
      instance_transforms: ${transforms.instance_transforms.inference}

fit_backend:
  _target_: src.datasets.TestBackend
  dataset: ${datasets.val}
  part: "fit"
  fit_split: 0.7                             
  random_seed: ${trainer.seed}

test_backend:
  _target_: src.datasets.TestBackend
  dataset: ${datasets.val}
  part: "test"
  fit_split: 0.7                              
  random_seed: ${trainer.seed}