train:
  _target_: src.datasets.DatasetCombine
  datasets:
    - _target_: src.datasets.BarkopediaDataset
      part: "train"
      train_split: 0.8
      num_classes: ${num_classes}
      instance_transforms: ${transforms.instance_transforms.train}
  num_local_classes:
    - ${num_classes}
  dataset_names:
    - barkopedia
val:
  _target_: src.datasets.DatasetCombine
  datasets:
    - _target_: src.datasets.BarkopediaDataset
      part: "val"
      train_split: 0.8
      num_classes: ${num_classes}
      instance_transforms: ${transforms.instance_transforms.inference}
  num_local_classes:
    - ${num_classes}
  dataset_names:
    - barkopedia
# test:
  # _target_: src.datasets.BarkopediaDataset
  # part: "test"
  # instance_transforms: ${transforms.instance_transforms.inference}
