train:
  _target_: torch.utils.data.ConcatDataset # we can concat datasets if we want to
  datasets:
    - _target_: src.datasets.BarkopediaDataset
      part: "train"
      train_split: 0.9
      instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.BarkopediaDataset
  part: "val"
  train_split: 0.9
  instance_transforms: ${transforms.instance_transforms.inference}
# test:
  # _target_: src.datasets.BarkopediaDataset
  # part: "test"
  # instance_transforms: ${transforms.instance_transforms.inference}
