defaults:
  - model: x_vector
  - writer: wandb
  - metrics: barkopedia
  - datasets: barkopedia
  - dataloader: basic
  - transforms: x_vector
  - batch_sampler: hpm
  - backends: all_backends
  - scheduler: cosine
  - _self_

sample_rate: 8000
yandex_token: null

optimizer:
  _target_: torch.optim.Adam
  weight_decay: 2e-5

base_lr: 1e-2
max_lr: 1e-2
base_lr_loss: 1e-2
max_lr_loss: 1e-2

loss_function:
  _target_: src.loss.AAMSoftmaxLoss
  embedding_dim: ${model.output_dim}
  scale: 30
  margin: 0.2
  label_smoothing: 0.1

trainer:
  log_step: 5
  n_epochs: 100
  device_tensors: ["spectral_feat", "label", "audio_lengths", "spectral_feat_lengths"]
  resume_from: null
  device: 'auto'
  allow_tf32: true
  accumulation_steps: 1 # gradient accumulation steps; >1 for effective larger batch size
  amp:
    enabled: false
    dtype: bfloat16
  compile:
    enabled: false
    call:
      _target_: torch.compile
      mode: default
      fullgraph: false
      dynamic: false
      backend: inductor
  override: False
  monitor: "max test_COS_Accuracy"
  save_period: 1
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
