train:
  audio:  # Resample audio to target sample rate first
    _target_: src.transforms.ResampleTransform
    target_sample_rate: ${sample_rate}
  get_spectral_feat: # special key for getting spectral_feat
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: ${sample_rate}
inference:
  audio:  # Resample audio to target sample rate first
    _target_: src.transforms.ResampleTransform
    target_sample_rate: ${sample_rate}
  get_spectral_feat:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: ${sample_rate}