train:
  get_feature: # special key for getting extracted_feature
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio: null # name of the tensor on which we apply transform
    # _target_: torchvision.transforms.v2.Compose
    # transforms:
    #   - _target_: src.transforms.wav_augs.Gain
inference:
  get_feature:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000