train:
  audio:  # Audio transforms applied to raw audio
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.ResampleTransform
        target_sample_rate: ${sample_rate}
      - _target_: src.transforms.MusanNoiseAugment
        download_dir: "data/augs/musan"
        noise_types: ["noise"]  # options: ["noise", "speech", "music"]
        snr_range: [10, 20]  # Signal-to-Noise Ratio in dB
        p: 0.5  # Probability of applying
        sample_rate: ${sample_rate}
      - _target_: src.transforms.RIRReverbAugment
        download_dir: "data/augs/reverb"
        p: 0.5  # Probability of applying
        sample_rate: ${sample_rate}

  get_spectral_feat:
    _target_: src.transforms.MfccExtractor
    sample_rate: ${sample_rate}
    n_mfcc: ${model.n_feats}
    hop_length_sec: 0.01      # 10 ms
    win_length_sec: 0.025     # 25 ms

inference:
  audio:  # Resample audio to target sample rate first
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.ResampleTransform
        target_sample_rate: ${sample_rate}

  get_spectral_feat:
    _target_: src.transforms.MfccExtractor
    sample_rate: ${sample_rate}
    n_mfcc: ${model.n_feats}
    hop_length_sec: 0.01
    win_length_sec: 0.025